export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const TITLE_CHANGED = 'TITLE_CHANGED';

//登录后，主界面展现的数据
export const FETCH_MENU_RESULT= 'FETCH_MENU_RESULT';
export const FETCHED_SCENEMUSIC_DATA= 'FETCHED_SCENEMUSIC_DATA';
export const RECEIVE_MENU_RESULT= 'RECEIVE_MENU_RESULT';
export const CHANGE_NAV_MENU= 'CHANGE_NAV_MENU';
export const CHANGE_MODULE= 'CHANGE_MODULE';

//音乐库情景列表
export const SCENE_LIST= 'SCENE_LIST';
//房间维护
export const FETCH_ROOM_RESULT='FETCH_ROOM_RESULT';
export const RECEIVE_ROOM_RESULT='RECEIVE_ROOM_RESULT';
export const ADD_ROOM='ADD_ROOM';
export const DELETE_ROOM='DELETE_ROOM';


//人员维护
export const FETCH_MAINTAIN_RESULT='FETCH_MAINTAIN_RESULT';
export const RECEIVE_MAINTAIN_RESULT='RECEIVE_MAINTAIN_RESULT';
export const RECEIVE_PERSON_INFO='RECEIVE_PERSON_INFO';
export const RECEIVE_EDIT_INFORMATION='RECEIVE_EDIT_INFORMATION';
export const RECEIVE_MODIFY_PASSWORD='RECEIVE_MODIFY_PASSWORD';

//情景维护
export const FETCH_SCENE_RESULT='FETCH_SCENE_RESULT';
export const RECEIVE_SCENE_RESULT='RECEIVE_SCENE_RESULT';
export const ADD_SCENE='ADD_SCENE';
export const DELETE_SCENE='DELETE_SCENE';

//推荐歌曲维护
export const FETCH_SONGS_RESULT='FETCH_SONGS_RESULT';
export const RECEIVE_SONGS_RESULT='RECEIVE_SONGS_RESULT';
export const ADD_SONGS='ADD_SONGS';
export const DELETE_SONGS='DELETE_SONGS';

//音乐库
export const FETCH_SCENEMUSIC_DATA='FETCH_SCENEMUSIC_DATA';
export const RECEIVE_SCENEMUSIC_DATA='RECEIVE_SCENEMUSIC_DATA';
export const SELECT_ROW_KEYS='SELECT_ROW_KEYS';
export const ADD_ROW_SCENE='ADD_ROW_SCENE';
export const DELETE_ROW_SCENE='DELETE_ROW_SCENE';
export const MODAL_VISIBLE='MODAL_VISIBLE';
export const FETCH_STOREMUSIC_DATA='FETCH_STOREMUSIC_DATA';
export const RECEIVE_STOREMUSIC_DATA='RECEIVE_STOREMUSIC_DATA';

//音乐分类
export const FETCH_MUSICSCENE_DATA='FETCH_MUSICSCENE_DATA';
export const RECEIVE_MUSICSCENE_DATA='RECEIVE_MUSICSCENE_DATA';

//客户端登录次数统计
export const FETCH_CLIENTLOGINACCOUNT_DATA='FETCH_CLIENTLOGINACCOUNT_DATA';
export const RECEIVE_CLIENTLOGINACCOUNT_DATA='RECEIVE_CLIENTLOGINACCOUNT_DATA';

//音乐统计
export const FETCH_MUSICSTATISTICAL_DATA='FETCH_MUSICSTATISTICAL_DATA';
export const RECEIVE_MUSICSTATISTICAL_DATA='RECEIVE_MUSICSTATISTICAL_DATA';

//标题栏维护数据
export const FETCH_PANELMAINTAIN_DATA='FETCH_PANELMAINTAIN_DATA';
export const RECEIVE_PANELMAINTAIN_DATA='RECEIVE_PANELMAINTAIN_DATA';

//审核
export const FETCH_AUDITMUSIC_DATA='FETCH_AUDITMUSIC_DATA';
export const RECEIVE_AUDITMUSIC_DATA='RECEIVE_AUDITMUSIC_DATA';

//声音创客
export const FETCH_MAKER_DATA='FETCH_MAKER_DATA';
export const RECEIVE_MAKER_DATA='RECEIVE_MAKER_DATA';